/**
 * Scene-authored audio (sfx-* nodes, sfx.* stream resources and the
 * connections that trigger them, generated by `pnpm audio:wire`) has no
 * legacy source. Conversion-parity tests compare authored scenes without it.
 */
export function withoutSceneAudio(scene) {
  const connections = (scene.connections ?? []).filter((connection) => !connection.target?.nodeId?.startsWith('sfx-'));
  const subresources = (scene.subresources ?? []).filter((resource) => !resource.resourceId.startsWith('sfx.') && !resource.resourceId.startsWith('music.'));
  const result = { ...scene, nodes: scene.nodes.filter((node) => !node.id.startsWith('sfx-')) };
  // Audio wiring may be the only reason a scene has connections at all.
  if (connections.length > 0) result.connections = connections;
  else delete result.connections;
  if (scene.subresources !== undefined) result.subresources = subresources;
  return result;
}
